/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ApiSubtitleRouteImport } from './routes/api/subtitle'
import { Route as SubtitlesSplatRouteImport } from './routes/subtitles.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitleRoute = ApiSubtitleRouteImport.update({
  id: '/api/subtitle',
  path: '/api/subtitle',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtitlesSplatRoute = SubtitlesSplatRouteImport.update({
  id: '/subtitles/$',
  path: '/subtitles/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/api/subtitle': typeof ApiSubtitleRoute
  '/subtitles/$': typeof SubtitlesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/api/subtitle': typeof ApiSubtitleRoute
  '/subtitles/$': typeof SubtitlesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/api/subtitle': typeof ApiSubtitleRoute
  '/subtitles/$': typeof SubtitlesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/manifest.json' | '/api/subtitle' | '/subtitles/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/manifest.json' | '/api/subtitle' | '/subtitles/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/manifest.json'
    | '/api/subtitle'
    | '/subtitles/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ApiSubtitleRoute: typeof ApiSubtitleRoute
  SubtitlesSplatRoute: typeof SubtitlesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitle': {
      id: '/api/subtitle'
      path: '/api/subtitle'
      fullPath: '/api/subtitle'
      preLoaderRoute: typeof ApiSubtitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtitles/$': {
      id: '/subtitles/$'
      path: '/subtitles/$'
      fullPath: '/subtitles/$'
      preLoaderRoute: typeof SubtitlesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ApiSubtitleRoute: ApiSubtitleRoute,
  SubtitlesSplatRoute: SubtitlesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
